
pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo Validacion de Variables recibidas a traves de Github Actions
    echo $(REPOSITORIO)
    echo $(STATUSACTION)
  displayName: 'Print variables'
#- task: azuredevopsgithub@0
#  inputs:
#    gitHubConnection: 'GitHub-token'
#    method: 'GET'
#    githubrestapiurl: 'https://api.github.com/repos/DevOps-Foundation-v3/pet-clinic/actions/artifacts/473249294/zip'

- script: |
    curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $(TOKEN-GITHUB)" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/DevOps-Foundation-v3/pet-clinic/actions/artifacts/473249294/zip -o $(Build.SourcesDirectory)
    #unzip $(Build.SourcesDirectory)/artefacto.zip
    ls
  displayName: Validacion descarga
  continueOnError: true