
pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo Validacion de Variables recibidas a traves de Github Actions
    echo $(REPOSITORIO)
    echo $(STATUSACTION)
  displayName: 'Print variables'
