
pool:
  vmImage: ubuntu-latest

steps:

- script: |
    echo Validacion de Variables recibidas a traves de Github Actions
    echo $(REPOSITORIO)
    echo $(STATUSACTION)
  displayName: 'Print variables'
- task: azuredevopsgithub@0
  inputs:
    gitHubConnection: 'GitHub-token'
    method: 'GET'
    githubrestapiurl: 'https://api.github.com/repos/DevOps-Foundation-v3/pet-clinic/actions/artifacts/473249294/zip'

- script: |
    unzip $(Build.SourcesDirectory)/Package.zip
    ls $(Build.SourcesDirectory) | grep zip
  displayName: Validacion descarga
  continueOnError: true